version: '3.8'

services:
  postgres:
    image: postgres:16
    container_name: leetcode_postgres
    restart: unless-stopped
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: leetcode
      POSTGRES_PASSWORD: leetcode
      POSTGRES_DB: leetcode
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
